version: 0.2

phases:

  # installing packages in the build environment
  install:
    runtime-versions:
      python: 3.x
    commands:
      - npm install
      - npm install -g mocha
      - npm install -g serverless

  # eg: install dependencies
  pre_build:
    commands:
      - pip install pytest

  # eg: build, run tests
  build:
    commands:
      - python -m pytest tests
      - serverless deploy -v
